=== DilanBn/DesarrolloDTD/src/espn.dtd
<!ELEMENT resultados (calendario)*>
<!ELEMENT calendario (partidojugado, partidoporjugar)*>
<!ELEMENT partidojugado (nombreequipo1, nombreequipo2, logo1, logo2, resultado, goles, goljugador, minutogol, tarjetasrojas, minutotarjetaroja)*>
<!ELEMENT nombreequipo1 (#PCDATA)>
<!ELEMENT nombreequipo2 (#PCDATA)>
<!ELEMENT logo1 (#PCDATA)>
<!ELEMENT logo2 (#PCDATA)>
<!ELEMENT resultado (#PCDATA)>
<!ELEMENT goles (#PCDATA)>
<!ELEMENT goljugador (#PCDATA)>
<!ELEMENT minutogol (#PCDATA)>
<!ELEMENT tarjetasrojas (#PCDATA)>
<!ELEMENT minutotarjetaroja (#PCDATA)>
<!ELEMENT partidoporjugar (nombreequipo1, nombreequipo2, logo1, logo2, racha, horapartido, diapartido)*>
<!ELEMENT racha (#PCDATA)>
<!ELEMENT horapartido (#PCDATA)>
<!ELEMENT diapartido (#PCDATA)>

=== DilanBn/DesarrolloDTD/src/espn.xml
<?xml version="1.0" encoding="UTF-8" ?>

<!DOCTYPE resultados SYSTEM "espn.dtd">

<resultados>
    <calendario>
        <partidojugado>
            <nombreequipo1></nombreequipo1>
            <nombreequipo2></nombreequipo2>
            <logo1></logo1>
            <logo2></logo2>
            <resultado></resultado>
            <goles></goles>
            <goljugador></goljugador>
            <minutogol></minutogol>
            <tarjetasrojas></tarjetasrojas>
            <minutotarjetaroja></minutotarjetaroja>
        </partidojugado>
        <partidoporjugar>
            <nombreequipo1></nombreequipo1>
            <nombreequipo2></nombreequipo2>
            <logo1></logo1>
            <logo2></logo2>
            <racha></racha>
            <horapartido></horapartido>
            <diapartido></diapartido>
        </partidoporjugar>
    </calendario>
</resultados>
